[server]
enableXsrfProtection = false
enableCORS = false
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#00d2ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1c24"
textColor = "#ffffff"
